spring.application.name=demo

# URL koneksi database (ganti 'nama_database_kamu' dengan nama DB di MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/demo_spring?useSSL=false&serverTimezone=UTC

# Kredensial MySQL
spring.datasource.username=root
spring.datasource.password=

# Konfigurasi Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
